# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YAbHDHj6DCvlpGFPofoaF6FtzifHO7yY
"""

import requests

link = 'https://'+input('Enter link to be tested\n')
try: 
  if requests.get(link).status_code == 200:
      print(link + ' is working')
except:
  print(link + ' is not working')

